### PR TITLE
Use useAuth context for useSWR fetcher

### PR DESCRIPTION
**Pull request by wr1159**
Fixes AdminUserManagement page to use UseAuth token instead of fetching from local storage

### CODE REVIEW

**Comment by jq1836** [comment]
Partially Resolves #86

**Review by jq1836 — CHANGES_REQUESTED** [review]
These changes will prevent admin users from accessing the page.

Need to handle the `unauthorised` and `isLoggedIn` states differently. Maybe use `auth?.user?.isAdmin` for `unauthorised` and `auth?.user != null` for `isLoggedIn`? This would also partially implement the FR in issue #22.

Also, noticed that using this implementation introduces a 5-10s delay before the `GET` request for the list of users is fired.

**Comment by wr1159** [comment]
> These changes will prevent admin users from accessing the page
>
> Need to handle the `unauthorised` and `isLoggedIn` states differently. Maybe use `auth?.user?.isAdmin` for `unauthorised` and `auth?.user != null` for `isLoggedIn`? This would also partially implement the FR in issue #22.

Ah I see, hmm maybe we can close this for now and fix it a bit later on together. Context is we saw that the useAuth wasnt being used so we thought to use it. 

> Also, noticed that using this implementation introduces a 5-10s delay before the `GET` request for the list of users is fired.

Hmm that's weird, could it be that the AuthContext is not passing the data fast enough?

**Comment by jq1836** [comment]
> Ah I see, hmm maybe we can close this for now and fix it a bit later on together. Context is we saw that the useAuth wasnt being used so we thought to use it.

I see, let's discuss this during the next meeting then, we'll then be able to have a consistent way of doing this. We don't have to close this, but can instead add onto this PR later on.

> Hmm that's weird, could it be that the AuthContext is not passing the data fast enough?

Went to investigate a bit and seems like AuthContext is not passing the data as soon as the component renders, it takes 1-2 rendering cycles before the auth value is populated. Seems like the 5-10s delay is a result of the SWR failing initially due to the lack of auth, but retrying 5-10s later.

**Pull request closed without merging**
